name: CI/CD (Hostinger LiteSpeed)

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_sqlite
          tools: composer:v2

      - name: Install dev dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run tests (SQLite)
        env:
          APP_ENV: test
          SYMFONY_DEPRECATIONS_HELPER: weak
        run: ./vendor/bin/phpunit -v

  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP for build
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl
          tools: composer:v2

      - name: Install prod dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      - name: Deploy via rsync (manual)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY:  ${{ secrets.SSH_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          set -e
          sudo apt-get update -y
          sudo apt-get install -y rsync

          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "${SSH_PORT:-22}" "$SSH_HOST" >> ~/.ssh/known_hosts

          rsync -az --delete \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="var/cache/*" \
            --exclude="var/log/*" \
            --exclude=".env" \
            --exclude=".env.test" \
            --exclude=".env.local" \
            -e "ssh -i ~/.ssh/id_ed25519 -p ${SSH_PORT:-22}" \
            ./ "${SSH_USER}@${SSH_HOST}:${REMOTE_PATH}"

      - name: Post-deploy on server (debug)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          debug: true
          script_stop: true
          script: |
            set -eux
            cd "${{ secrets.REMOTE_PATH }}" || { echo "❌ Bad REMOTE_PATH"; exit 1; }
            echo "PWD=$(pwd)"
            echo "Listing files:"
            ls -la

            # Write .env.local
            cat > .env.local <<EOF
            APP_ENV=prod
            APP_DEBUG=0
            APP_SECRET=${{ secrets.APP_SECRET }}
            DATABASE_URL="mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@${{ secrets.DB_HOST }}:3306/${{ secrets.DB_NAME }}?charset=utf8mb4"
            EOF

            mkdir -p var
            chmod -R a+rwX var

            echo "PHP version:"
            php -v || true

            # Sanity check Symfony is here
            test -f bin/console || { echo "❌ bin/console missing in $(pwd)"; exit 1; }

            # Show basic app info first
            php bin/console about --env=prod -vvv

            # Then cache + schema
            php bin/console cache:clear --env=prod -vvv
            php bin/console cache:warmup --env=prod -vvv
            php bin/console doctrine:schema:update --force --env=prod -vvv

